In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [51]:
from sklearn.datasets import load_iris
data1=load_iris()

In [52]:
data1.data
data1.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [53]:
data1.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [54]:
df=pd.DataFrame(data1.data,columns=data1.feature_names)

In [55]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [56]:
df['target']=data1.target

In [57]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [58]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [59]:
df = df[df['target'] != 2]
#df.drop(df[df['target'] == 2].index, inplace=True)

In [60]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


In [61]:
x=df.drop('target',axis=1)
y=df.target
x
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [62]:
#a=df.iloc[:,:-1]


In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=.2)


In [64]:

x_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
80,5.5,2.4,3.8,1.1
84,5.4,3.0,4.5,1.5
33,5.5,4.2,1.4,0.2
81,5.5,2.4,3.7,1.0
93,5.0,2.3,3.3,1.0
17,5.1,3.5,1.4,0.3
36,5.5,3.5,1.3,0.2
82,5.8,2.7,3.9,1.2
69,5.6,2.5,3.9,1.1
65,6.7,3.1,4.4,1.4


In [65]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()


In [66]:
logr.fit(x_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [67]:
y_test_pred_logr=logr.predict(x_test)
y_test_pred_logr

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0])

In [68]:
logr.predict_proba(x_test)# corresponding to higher probality classes is predicted 

array([[0.04043262, 0.95956738],
       [0.01046123, 0.98953877],
       [0.98706759, 0.01293241],
       [0.05440516, 0.94559484],
       [0.1383348 , 0.8616652 ],
       [0.97966131, 0.02033869],
       [0.98204504, 0.01795496],
       [0.03292232, 0.96707768],
       [0.03380573, 0.96619427],
       [0.00850516, 0.99149484],
       [0.02466034, 0.97533966],
       [0.97515854, 0.02484146],
       [0.00517837, 0.99482163],
       [0.00238366, 0.99761634],
       [0.0077453 , 0.9922547 ],
       [0.98619342, 0.01380658],
       [0.96597536, 0.03402464],
       [0.94907826, 0.05092174],
       [0.00735493, 0.99264507],
       [0.97742977, 0.02257023]])

In [69]:
from sklearn.metrics import r2_score,confusion_matrix,accuracy_score,classification_report
r2_score(y_test,y_test_pred_logr)

1.0

In [70]:
confusion_matrix(y_test,y_test_pred_logr)

array([[ 8,  0],
       [ 0, 12]])

In [71]:
print(classification_report(y_test,y_test_pred_logr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [72]:
from sklearn.metrics import roc_curve,auc
y_pred_proba=logr.predict_proba(x_test)[:,1]
y_pred_proba

array([0.95956738, 0.98953877, 0.01293241, 0.94559484, 0.8616652 ,
       0.02033869, 0.01795496, 0.96707768, 0.96619427, 0.99149484,
       0.97533966, 0.02484146, 0.99482163, 0.99761634, 0.9922547 ,
       0.01380658, 0.03402464, 0.05092174, 0.99264507, 0.02257023])

In [73]:
fpr,tpr,thresholds=roc_curve(y_test,y_pred_proba)

In [74]:
#understand roc curve properly what does  graph means

In [75]:
auc(fpr,tpr)

1.0

In [76]:
#cross validation , randomized search cv , grid search cv

In [77]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import KFold

In [78]:
cv=KFold(n_splits=5)
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [79]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(logr,x_train,y_train,cv=cv,scoring='accuracy')
scores


array([1., 1., 1., 1., 1.])

In [85]:
x=df.drop('target',axis=1)
y=df.target
x
y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=.2)
from sklearn.linear_model import LogisticRegression
# model
model = LogisticRegression(max_iter=300)

# ------------------- Simple K-Fold -------------------
kf = KFold(n_splits=5, shuffle=True, random_state=1)
kf_scores = cross_val_score(model, x, y, cv=kf, scoring='accuracy')

# ---------------- Stratified K-Fold -----------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)
skf_scores = cross_val_score(model, x, y, cv=skf, scoring='accuracy')

# results
print("K-Fold Accuracy scores:", kf_scores)
print("Mean K-Fold Accuracy:", kf_scores.mean())

print("\nStratified K-Fold Accuracy scores:", skf_scores)
print("Mean Stratified K-Fold Accuracy:", skf_scores.mean())


K-Fold Accuracy scores: [1. 1. 1. 1. 1.]
Mean K-Fold Accuracy: 1.0

Stratified K-Fold Accuracy scores: [1. 1. 1. 1. 1.]
Mean Stratified K-Fold Accuracy: 1.0


In [ ]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ---------------------------------------------------
# 1. Create binary classification data
# ---------------------------------------------------
X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=5,
    n_redundant=2,
    n_classes=2,
    random_state=1
)

# ---------------------------------------------------
# 2. Train–test split (hold-out test set)
# ---------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y
)

# ---------------------------------------------------
# 3. Cross-validation on TRAINING data only
# ---------------------------------------------------
model = LogisticRegression(max_iter=300)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)
cv_scores = cross_val_score(
    model, X_train, y_train, cv=skf, scoring='accuracy'
)

print("CV Accuracy scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

# ---------------------------------------------------
# 4. Train FINAL model on full training data
# ---------------------------------------------------
model.fit(X_train, y_train)

# ---------------------------------------------------
# 5. Predict on unseen TEST data
# ---------------------------------------------------
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

# ---------------------------------------------------
# 6. Evaluation on test set
# ---------------------------------------------------
print("\nTest Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


In [83]:
x=df.drop('target',axis=1)
y=df.target
x
y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=.2)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV,StratifiedKFold

params={"penalty":["l1","l2","elasticnet"],
        'C':[1,2,10,20,30,40]}

skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=1)
lr=LogisticRegression(solver="liblinear",
    max_iter=1000)
model1=GridSearchCV(lr,cv=skf,param_grid=params,verbose=2)
model1.fit(x_train,y_train)
model1.best_estimator_
print(model1.best_params_)

model1.best_score_
y_pred_model1=model1.best_estimator_.predict(x_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_model1))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_model1))
print("Classification Report:\n", classification_report(y_test, y_pred_model1))

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ............................C=1, penalty=elasticnet; total time=   0.0s
[CV] END ............................C=1, penalt