In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

In [45]:
from sklearn.datasets import load_iris
ld=load_iris()
x=ld.data
y=ld.target


In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

In [47]:
a=x_train

In [48]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
x_train=std.fit_transform(x_train)
x_test=std.fit_transform(x_test)

In [49]:
from sklearn.decomposition import PCA
pca=PCA()
x_train=pca.fit_transform(x_train)

In [50]:
pca.components_

array([[ 0.53412301, -0.22791604,  0.58442075,  0.5667621 ],
       [ 0.30791713,  0.94856275,  0.01976354,  0.07088833],
       [ 0.73832641, -0.18955246, -0.1347596 , -0.6330749 ],
       [-0.27344792,  0.11114341,  0.79993852, -0.52246697]])

In [51]:
x_train.shape

(105, 4)

In [52]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x_train=std.fit_transform(a)
x_train=pca.fit_transform(a)
pca.components_


array([[ 0.36760197, -0.06649071,  0.85410056,  0.36188398],
       [ 0.63470116,  0.7468054 , -0.17634312, -0.09131939],
       [ 0.58983791, -0.58428977, -0.06477864, -0.55362481]])

In [53]:
pca.explained_variance_ratio_

array([0.92935669, 0.04701035, 0.01924992])