In [1]:
# doing the minimum necessary imports
# more modules would be imported as and when needed

import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

# reading data from CSV file. 
# reading bank currency note data into pandas dataframe.
bankdata = pd.read_csv("bill_authentication.csv")  

# Exploratory Data Analysis
print(bankdata.shape)  
print("------------")
print(bankdata.head()) 
# 0=Fake Note, 1=Genuine Note

(1372, 5)
------------
   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0


In [2]:
# Data Preprocessing
# Data preprocessing involves 
# (1) Dividing the data into attributes and labels and 
# (2) dividing the data into training and testing sets.

# To divide the data into attributes and labels, do :
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class'] 

In [3]:
# the final preprocessing step is to divide data into training and test sets
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)

In [4]:
# TYPE your Code here
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
# class sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)

# Training the Algorithm. Here we would use simple SVM , i.e linear SVM
from sklearn.svm import SVC

# classifying linear data
svclassifier = SVC(kernel= 'linear') # classify linear data
# linear kernel is used when data is linearly separable. It is the simplest kernel function. It is given by the following equation:
# K(x, y) = x^T y + c
#svclassifier = SVC() # bydefault, its rbf
# rbf kernel is used when data is not linearly separable. It is given by the following equation:
# K(x, y) = exp(-gamma ||x - y||^2)
# kernel can take many values like
# Gaussian, polynomial, sigmoid, or computable kernel
# Gaussian kernel is used when data is not linearly separable. It is given by the following equation:
# K(x, y) = exp(-gamma ||x - y||^2)
# Polynomial kernel is used when data is not linearly separable. It is given by the following equation:
# K(x, y) = (gamma x^T y + coef0)^degree
# Sigmoid kernel is used when data is not linearly separable. It is given by the following equation:
# K(x, y) = tanh(gamma x^T y + coef0)

# When to use which kernel?
# If the data is linearly separable, then we can use linear kernel.
# If the data is not linearly separable, then we can use rbf, polynomial or sigmoid kernel.

# Any industry rule to decide which kernel to use?
# If the data is linearly separable, then we can use linear kernel.
# If the data is not linearly separable, then we can use rbf, polynomial or sigmoid kernel. 
# If the data is not linearly separable and we do not know which kernel to use, then we can use rbf kernel. It is the most commonly used kernel. It is a good default kernel to use when we do not know which kernel to use.

# fit the model over data
svclassifier.fit(X_train,y_train)

SVC(kernel='linear')

In [5]:
# Making Predictions
y_pred = svclassifier.predict(X_test)
y_pred_train = svclassifier.predict(X_train)


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score
# Training accuracy
print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
# Testing accuracy
print("Testing Accuracy:", accuracy_score(y_test, y_pred))

# Remember : for evaluating classification-based ML algo use  
# confusion_matrix, classification_report and accuracy_score.
# And for evaluating regression-based ML Algo use Mean Squared Error(MSE), ...

[[155   2]
 [  0 118]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       157
           1       0.98      1.00      0.99       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

Training Accuracy: 0.9881494986326345
Testing Accuracy: 0.9927272727272727


Note : to understand Precision, recall, f1-score, support; see this post
https://towardsdatascience.com/accuracy-precision-recall-or-f1-331fb37c5cb9

For example : In the above o/p -> (refer confusion matrix)
166/167 bank entries were correctly predicted false.
also, 108/108 bank entries were correctly predicted true.

The total no. of observations are also indicated as support. 
see support values -> for 0(i.e false) it is 167 and for 1(i.e true) it is 108 

further, Precision talks about how precise/accurate your model is ?
Precision tells us, out of those predicted positive, how many of them are actually positive. Our SVM model's precision is 1.00 i.e 100% in predicting the actual Negatives and 99% in predicting the actual positives. 

In [6]:
import seaborn as sns
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [7]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [8]:
# import some data to play with
irisdata = sns.load_dataset('iris')
irisdata.head()  # have a look at the attributres(=> X) and Labels(=> y)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [9]:
irisdata.shape

(150, 5)

In [10]:
irisdata.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
# Preprocessing data
X = irisdata.drop('species', axis=1)  
y = irisdata['species']

# Train Test Split
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)  

# Training the Algorithm
To train the kernel SVM, we use the same SVC class of the Scikit-Learn's svm library.

We will implement polynomial, Gaussian, and sigmoid kernels to see which one works better for our problem.

# 1. Polynomial Kernel
In the case of polynomial kernel, you also have to pass a value for the degree parameter of the SVC class. This basically is the degree of the polynomial. Take a look at how we can use a polynomial kernel to implement kernel SVM:

In [11]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8, gamma='auto')  
# more higher degree, 
# more time the system will take.u cn choose any no as degree
# gamma is optional. But it gives a FutureWarning. To avoid it , specify
# gamma as 'auto' or 'scale'
# degree is the degree of the polynomial kernel function ('poly'). Ignored by all other kernels. If gamma is 'auto', then 1/n_features will be used instead of gamma. If gamma is 'scale' (default) then it uses 1 / (n_features * X.var()) as value of gamma, where X is the training data.

svclassifier.fit(X_train, y_train)

# Making Predictions
# Now once we have trained the algorithm, 
# the next step is to make predictions on the test data.
y_pred = svclassifier.predict(X_test) 
y_pred_train = svclassifier.predict(X_train) 


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score
# Training accuracy
print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
# Testing accuracy
print("Testing Accuracy:", accuracy_score(y_test, y_pred))

# Note : Note the misclassification in 'virginica' species

[[152   5]
 [  1 117]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       157
           1       0.96      0.99      0.97       118

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

Training Accuracy: 0.99179580674567
Testing Accuracy: 0.9781818181818182


# 2. Gaussian Kernel

To use Gaussian kernel, you have to specify 'rbf' as value for the Kernel parameter of the SVC class.

In [12]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf', gamma='auto')  
svclassifier.fit(X_train, y_train) 

# Prediction and Evaluation
y_pred = svclassifier.predict(X_test)  
y_pred_train = svclassifier.predict(X_train)

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score
# Training accuracy
print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
# Testing accuracy
print("Testing Accuracy:", accuracy_score(y_test, y_pred))  

# Note : Note the best performance thats 100% precise

[[157   0]
 [  0 118]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       157
           1       1.00      1.00      1.00       118

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Training Accuracy: 1.0
Testing Accuracy: 1.0


# 3. Sigmoid Kernel
Finally, let's use a sigmoid kernel for implementing Kernel SVM. 
To use the sigmoid kernel, you have to specify 'sigmoid' as value for the kernel parameter of the SVC class.Take a look at the following script:  

In [13]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid', gamma='auto')  
svclassifier.fit(X_train, y_train)

# Prediction and Evaluation
y_pred = svclassifier.predict(X_test) 
y_pred_train = svclassifier.predict(X_train) 

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score
# Training accuracy
print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
# Testing accuracy
print("Testing Accuracy:", accuracy_score(y_test, y_pred))

# Note : Note the very poor perfomance from Sigmoid kernel

[[86 71]
 [51 67]]
              precision    recall  f1-score   support

           0       0.63      0.55      0.59       157
           1       0.49      0.57      0.52       118

    accuracy                           0.56       275
   macro avg       0.56      0.56      0.55       275
weighted avg       0.57      0.56      0.56       275

Training Accuracy: 0.5888787602552416
Testing Accuracy: 0.5563636363636364


# Comparison of Kernel Performance

If we compare the performance of the different types of kernels we can clearly see that the sigmoid kernel performs the worst. This is due to the reason that sigmoid function returns two values, 0 and 1, therefore it is more suitable for binary classification problems. However, in our case we had three output classes.

Amongst the Gaussian kernel and polynomial kernel, we can see that Gaussian kernel achieved a perfect 100% prediction rate while polynomial kernel misclassified three instances. Therefore the Gaussian kernel performed slightly better. However, there is no hard and fast rule as to which kernel performs best in every scenario. It is all about testing all the kernels and selecting the one with the best results on your test dataset.

In [ ]:
# Confusion Matrix:
# A confusion matrix is a table that is used to evaluate the performance of a classification algorithm. It is a 2x2 table that is used to evaluate the performance of a binary classification algorithm. It is also used to evaluate the performance of a multi-class classification algorithm. It is used to evaluate the performance of a classification algorithm by comparing the predicted labels with the true labels. It is used to evaluate the performance of a classification algorithm by calculating the number of true positives, true negatives, false positives and false negatives.
# Example of confusion matrix for binary classification for Cancer Detection:
#                 Predicted Positive    Predicted Negative
# Actual Positive     True Positive (TP)   False Negative (FN)
# Actual Negative     False Positive (FP)  True Negative (TN)
# Lets fill the confusion matrix for the above example:
#                 Predicted Positive    Predicted Negative
# Actual Positive     100                 20
# Actual Negative     10                  70
# Explaination of confusion matrix:
# True Positive (TP): The number of positive samples that are correctly classified as positive.
# False Negative (FN): The number of positive samples that are incorrectly classified as negative.
# False Positive (FP): The number of negative samples that are incorrectly classified as positive.
# True Negative (TN): The number of negative samples that are correctly classified as negative.
# In our example:
# 100: There are 100 people who actually have cancer and are correctly classified as having cancer.
# 20: There are 20 people who actually have cancer but are incorrectly classified as not having cancer.
# 10: There are 10 people who actually do not have cancer but are incorrectly classified as having cancer.
# 70: There are 70 people who actually do not have cancer and are correctly classified as not having cancer.