In [1]:
# doing the minimum necessary imports
# more modules would be imported as and when needed

import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

# reading data from CSV file. 
# reading bank currency note data into pandas dataframe.
bankdata = pd.read_csv("bill_authentication.csv")  

# Exploratory Data Analysis
print(bankdata.shape)  
print("------------")
print(bankdata.head()) 
# 0=Fake Note, 1=Genuine Note

(1372, 5)
------------
   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0


In [2]:

X = bankdata.drop('Class', axis=1)  
y = bankdata['Class'] 

In [3]:

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)

In [4]:
# TYPE your Code here
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
# class sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)

# Training the Algorithm. Here we would use simple SVM , i.e linear SVM
from sklearn.svm import SVC

# classifying linear data
svclassifier = SVC(kernel= 'linear') # classify linear data
# linear kernel is used when data is linearly separable. It is the simplest kernel function. It is given by the following equation:

# When to use which kernel?
# If the data is linearly separable, then we can use linear kernel.
# If the data is not linearly separable, then we can use rbf, polynomial or sigmoid kernel.

# Any industry rule to decide which kernel to use?
# If the data is linearly separable, then we can use linear kernel.
# If the data is not linearly separable, then we can use rbf, polynomial or sigmoid kernel. 
# If the data is not linearly separable and we do not know which kernel to use, then we can use rbf kernel. It is the most commonly used kernel. It is a good default kernel to use when we do not know which kernel to use.

# fit the model over data
svclassifier.fit(X_train,y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'linear'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",False
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [5]:

y_pred = svclassifier.predict(X_test)
y_pred_train = svclassifier.predict(X_train)



from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score

print("Training Accuracy:", accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:", accuracy_score(y_test, y_pred))


[[155   2]
 [  0 118]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       157
           1       0.98      1.00      0.99       118

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

Training Accuracy: 0.9881494986326345
Testing Accuracy: 0.9927272727272727


Note : to understand Precision, recall, f1-score, support; see this post
https://towardsdatascience.com/accuracy-precision-recall-or-f1-331fb37c5cb9

For example : In the above o/p -> (refer confusion matrix)
166/167 bank entries were correctly predicted false.
also, 108/108 bank entries were correctly predicted true.

The total no. of observations are also indicated as support. 
see support values -> for 0(i.e false) it is 167 and for 1(i.e true) it is 108 

further, Precision talks about how precise/accurate your model is ?
Precision tells us, out of those predicted positive, how many of them are actually positive. Our SVM model's precision is 1.00 i.e 100% in predicting the actual Negatives and 99% in predicting the actual positives. 

In [6]:
import seaborn as sns
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [7]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [8]:

irisdata = sns.load_dataset('iris')
irisdata.head() 

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [9]:
irisdata.shape

(150, 5)

In [10]:
irisdata.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [11]:
# Preprocessing data
X = irisdata.drop('species', axis=1)  
y = irisdata['species']

# Train Test Split
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)  

# 1. Polynomial Kernel
In the case of polynomial kernel, you also have to pass a value for the degree parameter of the SVC class. This basically is the degree of the polynomial. Take a look at how we can use a polynomial kernel to implement kernel SVM:

In [12]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8, gamma='auto')  
# more higher degree, 
# more time the system will take.u cn choose any no as degree
# gamma is optional. But it gives a FutureWarning. To avoid it , specify
# gamma as 'auto' or 'scale'
# degree is the degree of the polynomial kernel function ('poly'). Ignored by all other kernels. If gamma is 'auto', then 1/n_features will be used instead of gamma. If gamma is 'scale' (default) then it uses 1 / (n_features * X.var()) as value of gamma, where X is the training data.

svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test) 
y_pred_train = svclassifier.predict(X_train) 

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score

print("Training Accuracy:", accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:", accuracy_score(y_test, y_pred))



[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.92      0.96        13
   virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

Training Accuracy: 1.0
Testing Accuracy: 0.9666666666666667


# 2. Gaussian Kernel

To use Gaussian kernel, you have to specify 'rbf' as value for the Kernel parameter of the SVC class.

In [13]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf', gamma='auto')  
svclassifier.fit(X_train, y_train) 

# Prediction and Evaluation
y_pred = svclassifier.predict(X_test)  
y_pred_train = svclassifier.predict(X_train)

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
# Printing the accuracy score of the model
from sklearn.metrics import accuracy_score
# Training accuracy
print("Training Accuracy:", accuracy_score(y_train, y_pred_train))
# Testing accuracy
print("Testing Accuracy:", accuracy_score(y_test, y_pred))  



[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Training Accuracy: 0.975
Testing Accuracy: 1.0


# 3. Sigmoid Kernel
Finally, let's use a sigmoid kernel for implementing Kernel SVM. 
To use the sigmoid kernel, you have to specify 'sigmoid' as value for the kernel parameter of the SVC class.Take a look at the following script:  

In [14]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid', gamma='auto')  
svclassifier.fit(X_train, y_train)


y_pred = svclassifier.predict(X_test) 
y_pred_train = svclassifier.predict(X_train) 

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score

print("Training Accuracy:", accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:", accuracy_score(y_test, y_pred))



[[ 0  0 11]
 [ 0  0 13]
 [ 0  0  6]]
              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        11
  versicolor       0.00      0.00      0.00        13
   virginica       0.20      1.00      0.33         6

    accuracy                           0.20        30
   macro avg       0.07      0.33      0.11        30
weighted avg       0.04      0.20      0.07        30

Training Accuracy: 0.36666666666666664
Testing Accuracy: 0.2


c:\Users\Jagdish singh\jupyter311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Jagdish singh\jupyter311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Jagdish singh\jupyter311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


# Comparison of Kernel Performance

If we compare the performance of the different types of kernels we can clearly see that the sigmoid kernel performs the worst. This is due to the reason that sigmoid function returns two values, 0 and 1, therefore it is more suitable for binary classification problems. However, in our case we had three output classes.

Amongst the Gaussian kernel and polynomial kernel, we can see that Gaussian kernel achieved a perfect 100% prediction rate while polynomial kernel misclassified three instances. Therefore the Gaussian kernel performed slightly better. However, there is no hard and fast rule as to which kernel performs best in every scenario. It is all about testing all the kernels and selecting the one with the best results on your test dataset.